config/routes.rb
Rails.application.routes.draw do
  get 'schools/show'

  devise_scope :user do
    authenticated :user do
      root to: 'schools#show', as: :authenticated_root
    end
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end

    devise_for :users
  end

  resources :school_unities
  resources :school_classes
end

app/models/responsible.rb
class Responsible < ActiveRecord::Base
  validates_presence_of :name, :email
  validates_uniqueness_of :email

  has_and_belongs_to_many :students
  has_many :school_unities, through: :students
end

app/models/school.rb
class School < ActiveRecord::Base
  validates_presence_of :name, :cnpj
  validates_uniqueness_of :cnpj

  has_many :school_unities
  has_many :users
end

app/models/school_class.rb
class SchoolClass < ActiveRecord::Base
  validates_presence_of :name, :shift
  validates_uniqueness_of :name, scope: :shift

  enum shift: [
    :morning,
    :afternoon,
    :night
  ]

  belongs_to :school_unity
  has_and_belongs_to_many :students
end

app/models/school_unity.rb
class SchoolUnity < ActiveRecord::Base
  validates_presence_of :name, :address
  validates_uniqueness_of :name

  belongs_to :school
  has_many :school_classes
  has_and_belongs_to_many :teachers
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates_presence_of :name, :registration
  validates_uniqueness_of :registration

  has_and_belongs_to_many :school_classes
  has_and_belongs_to_many :responsibles
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  validates_presence_of :name, :registration
  validates_uniqueness_of :registration

  has_and_belongs_to_many :school_unities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  belongs_to :school
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/school_unities_controller.rb
class SchoolUnitiesController < ApplicationController
  before_action :set_school_unity, only: [:show, :edit, :update, :destroy]

  def index
    @school_unities = SchoolUnity.all
  end

  def show
  end

  def new
    @school_unity = SchoolUnity.new
  end

  def create
    @school_unity = SchoolUnity.new school_unity_params
    if @school_unity.save
      redirect_to school_unities_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @school_unity.update(school_unity_params)
      redirect_to school_unities_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to school_unities_path if @school_unity.destroy
  end

  private
  def set_school_unity
    @school_unity = SchoolUnity.find(params[:id])
  end

  def school_unity_params
    params.require(:school_unity).permit(:name, :address)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_filter :authenticate_user!

  def show
    @school_unities = current_user.school.school_unities
    @student_count = Student.count
    @responsible_count = Responsible.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors_message.html.erb
<% if object.errors.any? %>
    <div>
      <ul>
        <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_menu.html.erb
<div class="mdl-layout mdl-js-layout">
  <header class="mdl-layout__header mdl-layout__header--scroll">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title"><%= t('app_name') %></span>
      <div class="mdl-layout-spacer"></div>
        <%= link_to School.model_name.human, schools_show_path, method: :get, class: "mdl-navigation__link" %>
        <%= link_to SchoolUnity.model_name.human(count: 2), school_unities_path, method: :get, class: "mdl-navigation__link" %>
        <!--<a class="mdl-navigation__link" href=""><%= SchoolClass.model_name.human count: 2 %></a>-->
        <!--<a class="mdl-navigation__link" href=""><%= Teacher.model_name.human count: 2 %></a>-->
        <!--<a class="mdl-navigation__link" href=""><%= Student.model_name.human count: 2 %></a>-->
        <!--<a class="mdl-navigation__link" href=""><%= Responsible.model_name.human count: 2 %></a>-->
        <%= link_to t('logout'), destroy_user_session_path, method: :delete, class: 'mdl-navigation__link' %>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title"><%= t('app_name') %></span>
    <nav class="mdl-navigation">
      <%= link_to School.model_name.human, schools_show_path, method: :get, class: "mdl-navigation__link" %>
      <%= link_to SchoolUnity.model_name.human(count: 2), school_unities_path, method: :get, class: "mdl-navigation__link" %>
      <!--<a class="mdl-navigation__link" href=""><%= SchoolClass.model_name.human count: 2 %></a>-->
      <!--<a class="mdl-navigation__link" href=""><%= Teacher.model_name.human count: 2 %></a>-->
      <!--<a class="mdl-navigation__link" href=""><%= Student.model_name.human count: 2 %></a>-->
      <!--<a class="mdl-navigation__link" href=""><%= Responsible.model_name.human count: 2 %></a>-->
      <%= link_to t('logout'), destroy_user_session_path, method: :delete, class: 'mdl-navigation__link' %>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <div class="page-content"><%= yield %></div>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AgendaKidsTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
  <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
</head>
<body>
<%= render 'layouts/menu' if current_user%>

<%= yield unless current_user %>

</body>
</html>

app/views/school_unities/_form.html.erb
<div class='center form-card mdl-card mdl-shadow--3dp'>
  <%= render 'layouts/errors_message', object: @school_unity if @school_unity.errors.any? %>
  <%= form_for @school_unity do |f| %>
      <div class='field mdl-textfield mdl-js-textfield mdl-textfield--floating-label'>
        <%= f.label :name, class: 'mdl-textfield__label' %>
        <%= f.text_field :name, class: 'mdl-textfield__input' %>
      </div>
      <div class='field mdl-textfield mdl-js-textfield mdl-textfield--floating-label'>
        <%= f.label :address, class: 'mdl-textfield__label' %>
        <%= f.text_field :address, class: 'mdl-textfield__input' %>
      </div>
      <%= f.submit t('save'), class: 'login-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
  <% end %>
</div>

app/views/school_unities/edit.html.erb
<h3 class='form-title'><%= t('.edit_school_unity') %></h3>

<%= render 'form' %>

app/views/school_unities/index.html.erb
<h3 class='school-unity-title'><%= SchoolUnity.model_name.human count: 2 %></h3>

<table class='school-unity-title mdl-data-table mdl-js-data-table mdl-shadow--3dp'>
  <thead>
  <tr>
    <th class='mdl-data-table__cell--non-numeric'><%= SchoolUnity.human_attribute_name :name %></th>
    <th class='mdl-data-table__cell--non-numeric'><%= SchoolUnity.human_attribute_name :address %></th>
    <th colspan='3'></th>
  </tr>
  </thead>

  <tbody>
  <% @school_unities.each do |school_unity| %>
      <tr>
        <td class='mdl-data-table__cell--non-numeric'><%= school_unity.name %></td>
        <td class='mdl-data-table__cell--non-numeric'><%= school_unity.address %></td>
        <td>
          <%= form_for school_unity, method: :get do |f| %>
              <button class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored">
                <i class="material-icons">remove_red_eye</i>
              </button>
          <% end %>
        </td>
        <td>
          <%= form_for '', url: edit_school_unity_path(school_unity), method: :get do |f| %>
              <button class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored">
                <i class="material-icons">edit</i>
              </button>
          <% end %>
        </td>
        <td>
          <%= form_for school_unity, method: :delete, data: {confirm: t('confirm_destroy')} do |f| %>
              <button class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored">
                <i class="material-icons">delete</i>
              </button>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= form_for '', url: new_school_unity_path, method: :get do |f| %>
  <button class="fab-button mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
    <i class="material-icons">add</i>
  </button>
<% end %>

app/views/school_unities/new.html.erb
<h3 class='form-title' ><%= t('.new_school_unity') %></h3>

<%= render 'form' %>

app/views/school_unities/show.html.erb
<h3 class='form-title'><%= t('.show_school_unity') %></h3>
<div class='center show-card form-card mdl-card mdl-shadow--3dp'>
  <div class='field mdl-textfield mdl-js-textfield mdl-textfield--floating-label'>
    <%= label_tag SchoolUnity.human_attribute_name :name %>
    <h5><%= @school_unity.name %></h5>
  </div>
  <%= SchoolUnity.human_attribute_name :address %>
  <h5><%= @school_unity.address %></h5>
</div>

app/views/schools/show.html.erb
<h3 class="school-name-title"><%= current_user.school.name %></h3>

<table class='center mdl-data-table mdl-js-data-table mdl-shadow--3dp'>
  <thead>
  <tr>
    <th class='mdl-data-table__cell--non-numeric'><%= SchoolUnity.model_name.human count: 2 %></th>
    <th><%= SchoolClass.model_name.human count: 2 %></th>
    <th><%= Teacher.model_name.human count: 2 %></th>
    <th><%= Student.model_name.human count: 2 %></th>
    <th><%= Responsible.model_name.human count: 2 %></th>
  </tr>
  </thead>

  <tbody>
  <% @school_unities.each do |school_unity| %>
      <tr>
        <td class='mdl-data-table__cell--non-numeric'><%= school_unity.name %></td>
        <td><%= school_unity.school_classes.count %></td>
        <td><%= school_unity.teachers.count %></td>
        <td><%= Student.joins(:school_classes).where('school_classes.school_unity_id': school_unity.id).count %></td>
        <td><%= Responsible.joins(students: :school_classes).where('school_classes.school_unity_id': school_unity.id).count %></td>
      </tr>
  <% end %>
  </tbody>
</table>